# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "efichess"

[target.chess]
type = "executable"
sources = ["src/*.c"]
include-directories = ["include"]
clang.compile-options = ['-mno-stack-arg-probe'] # need to see workaround